import turtle
import time

turtle.Turtle()
window = turtle.Screen()
window.setup(width=1.0, height=1.0, startx=0, starty=0)
turtle.pensize(1)
turtle.shape("turtle")
turtle.hideturtle()


def first_page():
    turtle.hideturtle()
    turtle.bgcolor("black")
    turtle.color("white")
    turtle.penup()
    turtle.goto(0, 100)
    turtle.pendown()
    turtle.write("Midterm Project", font=("Helvetica", 35, "bold"), align="center")
    turtle.right(90)
    turtle.penup()
    turtle.fd(70)
    turtle.pendown()
    turtle.write("The Aries Constellation", font=("Helvetica", 35, "bold"), align="center")
    turtle.penup()
    turtle.fd(50)
    turtle.pendown()
    turtle.write("Jherlin Nuñez", font=("Helvetica", 22, "bold"), align="center")
    time.sleep(10)
    turtle.clear()


first_page()


def second_page():
    turtle.hideturtle()
    window.bgpic("aries.png")
    turtle.color("white")
    time.sleep(2)
    window.clear()


second_page()


def third_page():
    turtle.hideturtle()
    turtle.bgcolor("black")
    turtle.color("white")
    turtle.penup()
    turtle.goto(-250, -150)
    turtle.pendown()
    turtle.dot(11, "white")
    turtle.penup()
    turtle.goto(-250, -160)
    turtle.right(0)
    turtle.forward(20)
    turtle.pendown()
    turtle.write("Mesarthim", font=("Helvetica", 10, "bold"))
    turtle.penup()
    turtle.goto(-250, -150)

    turtle.left(110)
    turtle.pendown()
    turtle.forward(150)
    turtle.dot(10, "white")
    turtle.penup()
    turtle.goto(-290, -40)
    turtle.right(45)
    turtle.forward(20)
    turtle.pendown()
    turtle.write("Sheratan", font=("Helvetica", 10, "bold"))
    turtle.penup()
    turtle.goto(-301.30, -9.05)

    turtle.right(15)
    turtle.pendown()
    turtle.forward(300)
    turtle.dot(10, "white")
    turtle.penup()
    turtle.goto(-105, 190)
    turtle.right(0)
    turtle.forward(20)
    turtle.pendown()
    turtle.write("Hamal", font=("Helvetica", 10, "bold"))
    turtle.penup()
    turtle.goto(-108.46, 220.76)

    turtle.right(18)
    turtle.pendown()
    turtle.forward(70)
    turtle.dot(10, "white")
    turtle.penup()
    turtle.goto(-49.10, 230)
    turtle.right(0)
    turtle.forward(20)
    turtle.pendown()
    turtle.write("41 Ari", font=("Helvetica", 10, "bold"))
    turtle.penup()
    time.sleep(2)
    turtle.clear()
    turtle.reset()


third_page()


def fourth_page():
    # Stars background shows for 10 seconds
    turtle.hideturtle()
    window.bgpic("stars.png")
    turtle.bgcolor("black")
    turtle.color("white")

    # Stars are drawn illuminated
    turtle.penup()
    turtle.goto(-250, -150)
    turtle.pendown()
    turtle.dot(11, "purple")
    turtle.penup()
    turtle.left(110)
    turtle.forward(150)
    turtle.dot(10, "purple")
    turtle.penup()
    turtle.right(45)
    turtle.goto(-301.30, -9.05)
    turtle.right(15)
    turtle.forward(300)
    turtle.dot(10, "purple")
    turtle.penup()
    turtle.right(0)
    turtle.goto(-108.46, 220.76)
    turtle.right(18)
    turtle.forward(70)
    turtle.dot(10, "purple")
    turtle.penup()
    turtle.goto(-49.10, 257.85)

    # Names are shown one by one
    turtle.setheading(0)
    turtle.penup()
    turtle.goto(-250, -150)
    turtle.goto(-250, -160)
    turtle.right(0)
    turtle.forward(20)
    turtle.pendown()
    turtle.write("Mesarthim", font=("Helvetica", 10, "bold"))
    turtle.penup()
    turtle.goto(-250, -150)
    turtle.left(110)
    turtle.forward(150)
    turtle.goto(-290, -40)
    turtle.right(45)
    turtle.forward(20)
    turtle.pendown()
    turtle.write("Sheratan", font=("Helvetica", 10, "bold"))
    turtle.penup()
    turtle.goto(-301.30, -9.05)
    turtle.right(15)
    turtle.forward(300)
    turtle.goto(-105, 190)
    turtle.right(0)
    turtle.forward(20)
    turtle.pendown()
    turtle.write("Hamal", font=("Helvetica", 10, "bold"))
    turtle.penup()
    turtle.goto(-108.46, 220.76)
    turtle.right(18)
    turtle.forward(70)
    turtle.goto(-49.10, 230)
    turtle.right(0)
    turtle.forward(20)
    turtle.pendown()
    turtle.write("41 Ari", font=("Helvetica", 10, "bold"))
    turtle.penup()
    turtle.goto(-49.10, 257.85)

    # Connecting lines appear one by one
    turtle.setheading(0)
    turtle.goto(-250, -150)
    turtle.pendown()
    turtle.left(110)
    turtle.forward(150)
    turtle.right(60)
    turtle.forward(300)
    turtle.right(18)
    turtle.forward(70)
    time.sleep(2)


fourth_page()
